package com.literary.mapper;

import com.literary.model.course;
import com.literary.model.courseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface courseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int countByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insert(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insertSelective(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    List<course> selectByExample(courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    course selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") course record, @Param("example") courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExample(@Param("record") course record, @Param("example") courseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKeySelective(course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKey(course record);
}