package com.literary.mapper;

import com.literary.model.department;
import com.literary.model.departmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface departmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int countByExample(departmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByExample(departmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insert(department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insertSelective(department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    List<department> selectByExample(departmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    department selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") department record, @Param("example") departmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExample(@Param("record") department record, @Param("example") departmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKeySelective(department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_department
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKey(department record);
}