package com.literary.mapper;

import com.literary.model.employee;
import com.literary.model.employeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface employeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int countByExample(employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByExample(employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insert(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insertSelective(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    List<employee> selectByExample(employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") employee record, @Param("example") employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExample(@Param("record") employee record, @Param("example") employeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKeySelective(employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_employee
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKey(employee record);
}