package com.literary.mapper;

import com.literary.model.salary_detail;
import com.literary.model.salary_detailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface salary_detailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int countByExample(salary_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByExample(salary_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insert(salary_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insertSelective(salary_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    List<salary_detail> selectByExample(salary_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    salary_detail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") salary_detail record, @Param("example") salary_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExample(@Param("record") salary_detail record, @Param("example") salary_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKeySelective(salary_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_salary_detail
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKey(salary_detail record);
}