package com.literary.mapper;

import com.literary.model.student;
import com.literary.model.studentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface studentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int countByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insert(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int insertSelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    List<student> selectByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    student selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") student record, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByExample(@Param("record") student record, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKeySelective(student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbggenerated Tue May 07 13:34:43 CST 2019
     */
    int updateByPrimaryKey(student record);
}